### ISSUE TITLE
Enable piping the manifests through additional tools before writing to disk

### ISSUE THREAD

**Issue by hendrikmaus** [hendrikmaus/helm-templexer#61]
To support piping the manifests through additional tools, e.g. `kbld`, `helm-templexer` should support post-render hooks. So that users can define, that each call to `helm template (...)` should be piped through a tool of choice, for example yielding a command (per deployment) like `helm template <release-name> <chart-name> | kbld > <output-file>.yaml` (assuming that #36 is implemented as new default).

If we still plan to expose `helm`'s `--output-dir`, the implementation would need to handle that `helm` writes to disk directly.

**Comment by AlexanderThaller** [comment]
Need https://github.com/hniksic/rust-subprocess/pull/60 to be merged first.
