### ISSUE TITLE
Release an aarch64 build

### ISSUE THREAD

**Issue by art-shutter** [hendrikmaus/helm-templexer#95]
[This line](https://github.com/hendrikmaus/helm-templexer/blob/8b4022dedf67f84aafec41167c03f1c9f39d2324/.github/workflows/ci.yaml#L21) shows that the `aarch64` target for builds is enabled in the master branch. Could it be feasible to create a new release with this target build? Or, alternatively, if not all changes in master are ripe enough for a release, create a backport of changes that concern the build arch only and then release 2.0.1?

**Comment by hendrikmaus** [comment]
Hey @art-shutter, I will take a look at the matter shortly.

**Comment by hendrikmaus** [comment]
I will attempt a release of the current master branch.

**Comment by hendrikmaus** [comment]
Unfortunately the release process of this project is outdated and broken. I opened up #96 to modernise it though.

@art-shutter you can always install from source and target any commit like so, if that helps the immediate need:

```
# install the latest version found on crates.io
cargo install helm-templexer

# install a specific commit from source
cargo install helm-templexer --git https://github.com/hendrikmaus/helm-templexer.git --rev 9f75543330b5d10c0b7455a2c21af421802431d5
```

Of course, you have to have the Rust toolchain installed for that to work.
It will compile for your host architecture.

**Comment by art-shutter** [comment]
Thank you! Building locally is not an issue (builds fine), I needed some automation that would use a downloaded pre-built binary.

**Comment by hendrikmaus** [comment]
Let me see if I can add the pre-compiled binary to the latest release manually.

**Comment by hendrikmaus** [comment]
@art-shutter I manually added the `aarch63-apple-darwin` build inclduing checksums to the latest release https://github.com/hendrikmaus/helm-templexer/releases/tag/2.0.1

**Comment by art-shutter** [comment]
Thank you! This is exactly what I needed :)
